### ISSUE TITLE
Package nitrocli for Debian

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#10]
Do you have any objections against packaging nitrocli for Debian?

**Comment by d-e-s-o** [comment]
That would be great, I'd say. I don't use Debian, though, so that makes it pretty much a burden for me to maintain such a package. Would you mind taking that on?

**Comment by robinkrahl** [comment]
Yes, I’ll take care of that.  Generating the packages is done in a few minutes – the most complicated part is to wait for a Debian Developer to release it.  That said, I’d probably wait until the next release so that I do not have to package hid and hidapi-sys.  All other dependencies (after moving to libnitrokey) are already packaged.

**Comment by d-e-s-o** [comment]
> Yes, I’ll take care of that.

Thanks Robin!

Yep, it can wait. I plan to have one more release tagged (`0.1.3`) that contains the state before the removal of `hidapi` (that I am yet to look at...). I'll also take care of getting proper Gentoo ebuilds rolled out (I have a more or less stale one [here](https://github.com/d-e-s-o/nitrocli-ebuild)).

Anyway, what we can also do is upload the `.deb` packages to the "releases" page. I played around with that yesterday and it appears that we can upload and attach files even at a later point in time. So, say, if there is some value in providing a `.deb` for `0.1.3` we could upload that later.

**Comment by robinkrahl** [comment]
Current status:
- [`nitrokey-sys`](https://packages.debian.org/search?keywords=librust-nitrokey-sys-dev) is uploaded
- `nitrokey` is waiting for upload
- `argparse` is waiting for merge and upload
- `nitrocli` is blocked by `argparse` and `nitrokey`.  ITP bug report: [918069](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918069)

**Comment by d-e-s-o** [comment]
Heads up that `nitrocli` 0.2.1 has been [released](https://github.com/d-e-s-o/nitrocli/releases/tag/v0.2.1) that should include all the functionality we deemed necessary for the initial Debian release.

**Comment by robinkrahl** [comment]
Dependencies for the upcoming `nitrocli` version:
- [ ] `argparse`: waiting for merge and upload
- [ ] `base32`
- [x] `libc`
- [ ] `nitrokey`: waiting for upload
- [ ] `nitrokey-test`
- [x] `regex`

**Comment by robinkrahl** [comment]
Short version:  The `nitrocli` package will be a pre-built binary package.  Running the tests is not required for libraries and, as far as I know, binaries.  I did not yet find out whether the `debcargo` toolchain would support automatic test execution.

If you are interested in the long version, the [policy page](https://wiki.debian.org/Teams/RustPackaging/Policy) specifies the packaging process for Debian and Rust (and explains the difference between source packages, binary packages, libraries and applications).

**Comment by robinkrahl** [comment]
`nitrocli` has been [accepted](https://tracker.debian.org/news/1023515/accepted-rust-nitrocli-022-1-source-amd64-into-unstable-unstable/) into unstable, so I’m closing this issue.  As soon as it is available in testing – usually within five days –, I’ll create a pull request updating the readme.

**Comment by d-e-s-o** [comment]
Very nice! :+1: Thanks for making this happen.

**Comment by Dowwie** [comment]
I'm using Debian 8 Jessie.  The standard nitrokeyapp works with my system.  However, I did not manage to get neither the nitrocli crate nor the debian package in this thread to work.  In both cases, "nitrocli status" returns:  "Nitrokey device not found"
