### ISSUE TITLE
Pinentry error

### ISSUE THREAD

**Issue by 917Wolf** [d-e-s-o/nitrocli#105]
at 
```
nitrocli --version
nitrocli 0.3.1

gpg --version
gpg (GnuPG) 2.2.17
libgcrypt 1.8.5

hidapi-0.8.0

uname -r
5.4.17-ck
```
when I 
`nitrocli pws status` I get 
`83918929 No such file or directory <Pinentry>`

might be because i dont have ccid installed, but thats a wild guess.

**Comment by d-e-s-o** [comment]
Doesn't look like a `nitrocli` issue to me, but rather something wrong in the `pinentry` setup. I could be wrong, though.

Can you try running something like:
```bash
gpg-connect-agent 'GET_PASSPHRASE --data Nitrokey nitrocli:user:storage:0x00000000 + foobar Please+enter+something' /bye
```

and see whether it reports the same error?

**Comment by 917Wolf** [comment]
Yea, its not your fault the error gets passed through.
