### ISSUE TITLE
Re-evaluate tests::run::version_option test

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#114]
The `tests::run::version_option` test is currently disabled because clap used to print the version output directly to stdout.  This should be fixed (https://github.com/clap-rs/clap/issues/1390, https://github.com/clap-rs/clap/pull/1602), so we should check whether we can enable this test case.

**Comment by d-e-s-o** [comment]
I think I checked this not too long ago and my conclusion was that the change is only in the clap 3 branch. So we'll have to wait. Can double check again later today.

**Comment by d-e-s-o** [comment]
Confirmed the change is not prevent on `v2-master` and that the test still fails because data is printed to the real stdout.

```patch
--- src/tests/run.rs
+++ src/tests/run.rs
@@ -87,7 +87,6 @@ fn help_options() {
 }

 #[test]
-#[ignore]
 fn version_option() {
   // clap sends the version output directly to stdout: https://github.com/clap-rs/clap/issues/1390
   // Therefore we ignore this test for the time being.
@@ -100,6 +99,8 @@ fn version_option() {

     let s = String::from_utf8_lossy(&out).into_owned();
     let _ = re;
+    use std::io::Write;
+    writeln!(std::io::stdout(), "STDOUT: {}", s);
     assert!(re.is_match(&s), out);
   }

```

```
$ cargo test -- version_option --nocapture
running 1 test
nitrocli 0.3.3STDOUT:

thread 'tests::run::version_option' panicked at 'Box<Any>', src/tests/run.rs:104:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::run::version_option ... FAILED

failures:

failures:
    tests::run::version_option

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 64 filtered out

error: test failed, to rerun pass '--bin nitrocli'
```

**Comment by robinkrahl** [comment]
Thanks, I forgot about that.  I’ll check whether the patch can be
backported to v2.

**Comment by robinkrahl** [comment]
They consider this to be a feature, not a bug, so no backport for v2.
