### ISSUE TITLE
Support for Librem Key

### ISSUE THREAD

**Issue by insanerwayner** [d-e-s-o/nitrocli#130]
Getting:

```
$ nitrocli config get
Nitrokey device not found

Caused by:
     Unsupported Nitrokey model
```

libnitrokey 3.6 now supports Librem Key and the Nitrokey App is working as expected.

**Comment by d-e-s-o** [comment]
Support for Librem Key will arrive once https://github.com/d-e-s-o/nitrocli/pull/129 lands.

**Comment by d-e-s-o** [comment]
Support for Librem Key landed in `devel`. Not sure when the next release will be cut, though. Right now we are semi-blocked on `envy` not fixing their stuff up.

**Comment by insanerwayner** [comment]
All my tests so far on `devel` seem to be working with the Librem Key

**Comment by d-e-s-o** [comment]
Great, thanks for verifying that! We will need to fix up `nitrokey-test` and run all tests on it before the code can be released, though. Haven't had the time to look at that.

**Comment by d-e-s-o** [comment]
Supported in [`v0.4.0`](https://github.com/d-e-s-o/nitrocli/releases/tag/v0.4.0).
