### ISSUE TITLE
Allow spaces in OTP base32 secret

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#136]
Some sites display the base32 secret for OTP authentication in groups, separated by spaces.  nitrocli should be able to handle such input without requiring the user to manually remove the spaces.

**Comment by d-e-s-o** [comment]
Can you provide an example please? I am not sure I fully understand what groups you are referring to.

**Comment by robinkrahl** [comment]
Groups of four characters, e. g. `1234 5678 9012 3456`.
