### ISSUE TITLE
Update help text for otp set

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#137]
Since https://github.com/d-e-s-o/nitrocli/commit/99fde3cac7c9cf278b81876994d3a4f4b795b8ce, the default is base32, not hexadecimal.

```rust
  /// The secret to store on the slot as a hexadecimal string (or in the format set with the
  /// --format option)
  pub secret: String,
```

https://github.com/d-e-s-o/nitrocli/blob/master/src/args.rs#L292

**Comment by d-e-s-o** [comment]
Will fix it. Thanks for the report!

**Comment by d-e-s-o** [comment]
Should be fixed now.
