### ISSUE TITLE
List libnitrokey version

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#147]
Knowing the libnitrokey version used by nitrocli is an important information for debugging.  Currently, it is impossible to determine the library version unless nitrocli is linked against a shard libnitrokey.  We should probably have a version command that lists both the nitrocli version and the libnitrokey version as returned by `nitrokey::get_library_version()`.

**Comment by d-e-s-o** [comment]
I agree, but can we just include that in the `-V`/`--version` output please? I don't see the point in having a dedicated command for that.

**Comment by robinkrahl** [comment]
Good point!  I missed that because it didn’t turn up in `grep version -r src`.
