### ISSUE TITLE
Compare strings instead of byte slices in tests

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#152]
In some tests – for example `status::not_found_raw` –, we compare byte slices with `assert_eq!`.  This results in an error message that is very hard to read, see for example [this log](https://github.com/robinkrahl/nitrocli/runs/2354684671#step:7:446).  Creating a string with `String::from_utf8_lossy` and comparing it to a string value would be functionally identical but much easier to read.

**Comment by robinkrahl** [comment]
Alternatively, the string representation could be used in the assert message.

**Comment by d-e-s-o** [comment]
> Alternatively, the string representation could be used in the assert message.

Sounds good to me, let's do that.
