### ISSUE TITLE
"Unexpected response: OK" if empty password is entred via pinentry

### ISSUE THREAD

**Issue by bircoph** [d-e-s-o/nitrocli#176]
Hi!

During investigation of issue #175 I found that nitrocli-0.4.0 fails to recognize pinentry's response when empty password is provided and OK button is pressed (or just hit the Enter):
```
$  nitrocli pws get 1
Failed to parse pinentry secret

Caused by:
    Unexpected response: OK
```
If cancel is pressed (or Esc) response is more reasonable:
```
$  nitrocli pws get 1
Failed to parse pinentry secret

Caused by:
    83886179 Operation cancelled <Pinentry>
```
Why I need to enter empty password in the first place? Due to bug #175 the first entered password will be discarded regardless of whether it is valid or not, so to save time I tried just to skip it by pressing Enter and found another issue.

**Comment by d-e-s-o** [comment]
Thanks for opening an issue. It's easy to reproduce.

Response when we enter something:
```
$ gpg-connect-agent 'GET_PASSPHRASE --data cacheid errormsg prompt description' '/bye'
D hallo
OK
```

Response when we enter nothing:
```
$ gpg-connect-agent 'GET_PASSPHRASE --data cacheid errormsg prompt description' '/bye'
OK
```

We were always under the impression that there would be a `D` line.
