### ISSUE TITLE
nitrocli (for NK2 Pro) not responsive while NK3 plugged in

### ISSUE THREAD

**Issue by KaoriRinaFujimoto** [d-e-s-o/nitrocli#188]
first of all thanks for this great utility.  
Been using nitrocli with my NK2 Pro for the past 1.5 years and everything has been working great so far when using by itself.   

However recently I've received my NK3s and set them up to use for webauth (FIDO2) and SSH into all my machines. Since NK3 doesn't support PGP operations and password management (yet) I'm going to use both devices -- which is not a huge deal, except that nitrocli won't respond once the NK3 is plugged in.  

I'm running nitrocli v 0.4.1 on arch and can access my NK2 Pro perfectly fine while plugged in alone.  
Once I plug in a NK3 nitrocli won't respond anymore to basic commands like `nitrocli list` or `nitrocli status`. I've tried all available USB A ports on my PC / dock without success. Running `journalctl -f` shows that both NKs are being recognized by the system.  
Even referring to the NK2 Pro by serial number with `nitrocli status --serial-number 0x0000abcd` or USB path `nitrocli status --usb-path 1-2:3.4` does not work. Running these commands with highest verbosity unfortunately does not output anything as well. 

Once I unplug the NK3 everything works well again.  

Is anyone having similar issues or any ideas how to troubleshoot that?
Thanks

**Comment by robinkrahl** [comment]
Thanks for the report!  This is a [known issue in libnitrokey][0] and will be [fixed][1] with the next release.

[0]: https://github.com/Nitrokey/libnitrokey/issues/193
[1]: https://github.com/Nitrokey/libnitrokey/pull/195

Possible workarounds until the release:
- Compile libnitrokey from the current master, install it and set the `USE_SYSTEM_LIBNITROKEY` environment variable while compiling `nitrocli`.
- Change `Cargo.toml` to use a local copy of `nitrokey-sys` and apply the linked patch to the libnitrokey source included in `nitrokey-sys`.

**Comment by d-e-s-o** [comment]
Thanks for the quick analysis (and the fix!) @robinkrahl! I see libnitrokey v3.7 has been cut and includes the fix. Will you update `nitrokey-sys` to use this new version so that we can have the issue fixed in `nitrocli`?

**Comment by KaoriRinaFujimoto** [comment]
just wanted to thank you guys for the quick fix! Working like a charm

**Comment by robinkrahl** [comment]
Thanks for the report!  This is a known issue in libnitrokey [0] and
will be fixed [1] with the next release.

[0] https://github.com/Nitrokey/libnitrokey/issues/193
[1] https://github.com/Nitrokey/libnitrokey/pull/195
