### ISSUE TITLE
Add --debug option

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#32]
Add a `--debug` option that enables debugging output from `libnitrokey` ([`nitrokey::set_debug`](https://docs.rs/nitrokey/0.2.1/nitrokey/fn.set_debug.html)).

**Comment by d-e-s-o** [comment]
I went with `-v`/`--verbose` which provides a more fine granular control of the log level (see ull request https://github.com/d-e-s-o/nitrocli/pull/44). I don't thinkg we need a `--debug` in addition to that. Thanks for bringing this up, Robin!
