### ISSUE TITLE
Check and set time on Nitrokey

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#34]
TOTP generation requires that the Nitrokey’s clock is synced.  We should provide a command to set the clock to a given value and/or to synchronize it with the system clock.  We could even consider to print a warning if the user tries to generate a TOTP on an out-of-sync device.

In my opinion, this is the last major issue to take care of before the next release.

**Comment by d-e-s-o** [comment]
Sounds good! In retrospect I would really have liked to cut a release earlier. We are cramming a lot of features into this one, for no real reason. In my opinion it would have been much better to ship, say the `pws` and `volume` command introduction and that's it. The rest would come as smaller incremental updates. That would have allowed us to focus on testing (I expect it to be much harder to roll out proper testing now and to think about the corner cases that we would have more easily thought of during feature development) and less features would have meant an easier time getting the documentation up to date (although admittedly that is not a big deal).

But we have what we have (and lack of testing hardware certainly was a factor), so no pulling back now. So yes, given that this sounds like an impediment to the functioning of already merged functionality we should add support for clock synchronization. Will that require an additional dependency (if we decide go with reading the host time)?

**Comment by robinkrahl** [comment]
To be honest, I just forgot about this issue because it was six months
since I implemented the OTP support in `nitrokey`.  After thinking about
the issue some more, I think it would be best to add a `--time` option
to the `otp get` command.  Then we could always set the time before
generating the OTP – either to the system time or to the given timestamp
if `--time` is set.

> Will that require an additional dependency (if we decide go with
> reading the host time)?

No.  We can use `std::time::SystemTime`.  All in all, this is only a
minor change.  I just wanted to file an issue so that we do not forget
about it.

**Comment by d-e-s-o** [comment]
> To be honest, I just forgot about this issue because it was six months since I implemented the OTP support in `nitrokey`. After thinking about the issue some more, I think it would be best to add a `--time` option to the `otp get` command. Then we could always set the time before generating the OTP – either to the system time or to the given timestamp if `--time` is set.

Sure, no worries. My remarks were more of a general nature than specific to this issue (so perhaps that wasn't the best place to articulate them). So the interface you propose is:
- `nitrocli otp get --time` would automatically sync the time to the host time, if it is out of sync.
- `nitrocli otp get` would warn if out-of-sync.

Is that right? I think I may have to understand OTP a little more. What would be considered out-of-sync? Is that time window dependent?

> Will that require an additional dependency (if we decide go with reading the host time)?
> No. We can use `std::time::SystemTime`.

Ah, perfect!

> All in all, this is only a minor change. I just wanted to file an issue so that we do not forget about it.

Absolutely.

**Comment by robinkrahl** [comment]
My proposal is:
- `nitrocli otp get` always sets the Nitrokey time to the system time
- `nitrocli otp get --time <ts>` sets the Nitrokey time to <ts>

Basically, HOTP generates an OTP by hashing a counter and the secret.
TOTP uses time mod time_window as the counter, where time is the current
time in seconds and time_window is variable but typically 30s.

So the authentication fails if T_N != T_A (mod time_window), where T_A
is the time when the application validates the OTP and T_N is the time
when the Nitrokey generates the OTP (according to the respective system
clock).  Most applications also accept the next or previous OTP (i. e. a
deviation of one time_window).  This means that a deviation of a few
seconds is fine, a deviation of up to 60 seconds might cause occasional
errors, and more than one minute deviation will fail all auhentication
attempts.

Possible problems with this solution are:
- We have one more command to send to the device (set time).  But on the
  other hand, we should always check the time, so it does not make any
  difference.
- The system clock might be out of sync.  But I think this should be a
  rather rare exception.
- The application clock might be out of sync.  But there’s nothing we
  can do about that anyway.

There could be a case where a user only deals with a single application
that is known to have a wrong time and therefore wants the Nitrokey to
run with that time without nitrocli resetting the clock.  But I consider
that highly unlikely.  We could still add a `--no-system-time` option to
deal with this problem should it ever occur.

Alternative approaches are.
- Provide a `nitrocli otp sync` command and warn in `otp get` if the
  time is out of sync.
- Only set the time if the user sets the `--system-time` options.

**Comment by d-e-s-o** [comment]
Many thanks for the explanation!

There are two more things that I am confused about, I guess.
1) From your description it appears that the Nitrokey (or any TOTP capable device) really needs to have a way to keep time. But the device has no battery (from what I know), so it cannot do anything of that sort if it is unplugged. Is that why you would want to set the time by default? Because it is very likely out of sync?
2) Are there other services that use the time? If OTP is the sole user I think unconditionally syncing it is fine.

> Possible problems with this solution are:
> - We have one more command to send to the device (set time). But on the other hand, we should always check the time, so it does not make any difference.

We would also need to retrieve the currently set time window, wouldn't we? (though that may come along with the time; not that this is a problem, I just want to understand)

**Comment by robinkrahl** [comment]
> 1) From your description it appears that the Nitrokey (or any TOTP
> capable device) really needs to have a way to keep time. But the
> device has no battery (from what I know), so it cannot do anything of
> that sort if it is unplugged. Is that why you would want to set the
> time by default? Because it is very likely out of sync?

As far as I know, the Nitrokey devices do not have a RTC and do not keep
time.  So some kind of synchronization is always necessary (see below
for the nitrokey-app implementation).

> 2) Are there other services that use the time? If OTP is the sole user
> I think unconditionally syncing it is fine.

Yes, as far as I know.  The corresponding libnitrokey function is called
`NK_totp_set_time`, and its comment says:  “Set time on the device (for
TOTP requests)”.  Also, I don’t know of any other application that could
use the time.

> We would also need to retrieve the currently set time window, wouldn't we?

No, only the slot name is readable.  The other information, including
the time window, are not exposed by the firmware.  We would have to use
heuristics.

---

I had a look at the nitrokey-app implementation, and I found some lost
memories.  In fact, there are two commands to set the time: get_time
(sic!) and set_time.  Please see nitrokey/libnitrokey#114 [0] for
details.  I could not use `get_time` in the `nitrokey` crate due to the
bugged C API, and I have not yet implemented the new
`NK_totp_set_time_soft` as I did not think it would be needed in the
beginning.

nitrokey-app always tries to update the time using
get_time/set_time_soft.  If this fails, it warns the user and offers to
perform a “hard” set_time call.  See nitrokey-app/mainwindow.cpp:381 [1]
for the implementation details.

[0] https://github.com/Nitrokey/libnitrokey/pull/114
[1] https://github.com/Nitrokey/nitrokey-app/blob/6b6cd2fe31dd3bb2910c13acb480e8f15b33fac9/src/ui/mainwindow.cpp#L381

**Comment by szszszsz** [comment]
Hi! Just wanted to add two words. 
Internal clock synchronization should be required only once per device's power cycle. It should keep the time then for further TOTP work. I do not know, how much its clock drifts with time, but never seen any issues during normal usage. Devices have no battery, hence the clock is reset on each boot.

**Comment by d-e-s-o** [comment]
> ...
> Please not that the comment continues after the three dots, even if Github thinks that’s a signature. Also, as I cannot edit comments submitted by mail, I want to make clear that nitrokey-app only sets the time once a device is connected, not with every OTP generation.

Thanks for the explanation @robinkrahl ! No more questions at this point, your honor.

> In conclusion, I think my previous suggestion is still valid. But we could use the `*_soft` function per default. If it fails, the user has to pass `--ignore-time` to continue anyway or `--reset-time` for a “hard” reset.

Sounds good to me!

> Internal clock synchronization should be required only once per device's power cycle. It should keep the time then for further TOTP work. I do not know, how much its clock drifts with time, but never seen any issues during normal usage. Devices have no battery, hence the clock is reset on each boot.

Thanks for the clarification @szszszsz !

**Comment by robinkrahl** [comment]
I haven’t started working on it yet, but I can take care of it.
Shouldn’t be a big change.

**Comment by d-e-s-o** [comment]
Merged. Thanks for bringing up this issue and resolving it @robinkrahl !
