### ISSUE TITLE
Upstream Gentoo ebuild

### ISSUE THREAD

**Issue by d-e-s-o** [d-e-s-o/nitrocli#41]
We have a [Gentoo ebuild](https://github.com/d-e-s-o/nitrocli-ebuild) that I recently got up to speed again but it has to be imported by hand and it would be much nicer to have this functionality in the official Gentoo Portage tree or at least some semi-official overlay.

We should also add instructions on how to package for Gentoo to `doc/packaging.md`.

**Comment by d-e-s-o** [comment]
Request is tracked by https://bugs.gentoo.org/674200 & https://github.com/gentoo/gentoo/pull/10714

**Comment by d-e-s-o** [comment]
W00t! `app-crypt/nitrocli-0.1.3` just landed in the official Gentoo Portage tree! :-)

I sincerely hope that pushing an ebuild for `0.2.0` out there will be less painful.

**Comment by robinkrahl** [comment]
Nice!  Based on the macOS discussion, did you test the package on a system without libnitrokey and nitrokey-app (i. e. without the udev rules)?

In Debian, I patched the `nitrokey-sys` crate to use the system `libnitrokey` (which ships the udev rules).  It would probably make sense to do the same for Arch and Gentoo.  I’ll try to think of a better solution than patching the build script for the next `nitrokey-sys` release.

**Comment by d-e-s-o** [comment]
For whatever reason those rules do not seem to be required on Gentoo. I never set them up/installed them. Installing the ebuild on a live system just worked. I haven't investigated why exactly that is.
I'll try again with `0.2.0` once that is packaged, because I am not sure if the switch to using `libnitrokey` changed anything, but it worked on my system so far.

**Comment by d-e-s-o** [comment]
Upstreaming of `v0.2.0` is tracked via https://github.com/gentoo/gentoo/pull/10742

**Comment by d-e-s-o** [comment]
Version `0.2.0` is now also available in the official Gentoo Portage tree!
https://packages.gentoo.org/packages/app-crypt/nitrocli

Future versions will be packaged and upstreamed roughly as they are released.
