### ISSUE TITLE
Support base32 OTP secrets

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#46]
Apparently, the de-facto standard set by Google Authenticator is sharing OTP secrets as base32 strings.  We should support this input type in `otp set`.  I suggest to replace the `--ascii` option with a `--format [ascii|hex|base32]` option.

**Comment by d-e-s-o** [comment]
Interesting. The suggestion sounds good! Do you plan to take care of that, @robinkrahl ?

**Comment by robinkrahl** [comment]
I added it to the list in the wiki.  Probably, but I’ve got some other things to investigate first.

**Comment by robinkrahl** [comment]
I’ll need an additional dependency, [`base32`][], to implement this.  Do you have an automated solution to add a crate and its dependencies to the repository or do you manually add them?  Also this crate depends on `rand` ^0.5.5 while we currently have v0.6.1.  Should we patch one of the crates to only have one `rand` version or should we include both?

[`base32`]: https://crates.io/crates/base32

**Comment by d-e-s-o** [comment]
> Do you have an automated solution to add a crate and its dependencies to the repository or do you manually add them? 

I manually add them. Don't worry about it, just update `Cargo.toml` and I'll take care of it before merging.

> Also this crate depends on rand ^0.5.5 while we currently have v0.6.1. Should we patch one of the crates to only have one rand version or should we include both?

I checked and it's a dev-dependency. I am fine not vendoring those (and since it won't be included in the having two versions consumed is fine), so we should be good.

**Comment by robinkrahl** [comment]
Done with #49.
