### ISSUE TITLE
Hanging Nitrokey when switching between nitrocli and GnuPG

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#47]
You already mentioned this problem in [this a request](https://github.com/d-e-s-o/nitrocli/pull/29):
> Btw., this has bugged me for ages: does your nitrokey "hang" frequently? E.g., when I am using gpg and then nitrocli the red light just stays on and the key won't do anything or take ages to respond (sometimes it just responds with garbage after a long time). I have to disconnect and reconnect (physically) to get it into a working state again. I am still on firmware version 0.47 (but plan to upgrade soon). I think later today I can check whether my testing stick has the same problem.

I could not reproduce this at the time (as I only used my Storage for development and my Pro for GnuPG), but since I use nitrocli on my Pro too, I experience the same problem.  Today I managed to reproduce it.  This is a tracking issue for the [upstream issue](https://github.com/Nitrokey/libnitrokey/issues/137).

**Comment by d-e-s-o** [comment]
I don't see what we can do here on the `nitrocli` side of things. @szszszsz has been able to reproduce the issue, confirmed it has to do with the firmware, and seemingly gotten somewhat closer to a solution. I gather we can't do much other than wait. Closing.
