### ISSUE TITLE
Do we want to support old firmware versions?

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#62]
I’m currently implementing support for setting the access mode (read-only, read-write) for the Storage.  Here we have two issues:
1. Setting the access mode for the encrypted storage is only supported in firmware version 0.49 (0.50 released on 2018-01-21).
2. Setting the access mode for the unencrypted storage required the user PIN instead of the admin PIN in firmware versions 0.50, 0.48 and below (0.51 released on 2018-06-14).

Do we want to support the old behavior?  On the one hand, it is code that I cannot test, and there is no technical reason not to upgrade the firmware.  On the other hand, people might not want to update the firmware unless required, especially as the process can be tricky for new users.

I think it is reasonable not to support old firmware versions, especially if they are older than 6 months (as in this case).  Do you agree?

Edit:  Of course I’m only talking about the Storage where users can upgrade the firmware.  For the Pro, we should support as many firmware versions as possible.

**Comment by d-e-s-o** [comment]
Oh yeah, I noticed that too.

> I think it is reasonable not to support old firmware versions, especially if they are older than 6 months (as in this case). Do you agree?

Yeah, I don't consider that a big problem.

**Comment by robinkrahl** [comment]
Okay, I documented the outdated functions as not supported.
