### ISSUE TITLE
Tag and sign releases

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrocli#8]
Having tags for version releases would make it easier to navigate the repository.  Signing these tags would make it easier to verify the code, especially as GitHub seems to throw away commit signatures from pull requests (probably because they are rebased).

**Comment by d-e-s-o** [comment]
Yeah I can look into that.

> GitHub seems to throw away commit signatures from pull requests (probably because they are rebased)

I had noticed that, too. I used the UI once...and that's what came out of it :D

**Comment by d-e-s-o** [comment]
Alright. Signed tags available. Let me know if you find something that I missed.

**Comment by d-e-s-o** [comment]
@robinkrahl can you check whether https://api.github.com/users/d-e-s-o/gpg_keys helps? You are right, I haven't pushed it to any "official" key servers.

**Comment by robinkrahl** [comment]
@d-e-s-o I don’t think so.  Quoting from the [API documentation](https://developer.github.com/v3/users/gpg_keys/) for `gpg_keys`:

> The data returned in the `public_key` response field is not a GPG formatted key. When a user uploads a GPG key, it is parsed and the cryptographic public key is extracted and stored. This cryptographic key is what is returned by the APIs on this page. This key is not suitable to be used directly by programs like GPG.

If you do not want to upload it to a keyserver, you could add it as a file to the repository or to this issue.
