### ISSUE TITLE
storage subcommand structure

### ISSUE THREAD

**Issue by d-e-s-o** [d-e-s-o/nitrocli#80]
I am considering changing the structure of the `storage` subcommand. Currently we have:

- `storage`
  - `status`
  - `close`
  - `open`
  - `hidden`
    - `create`
    - `close`
    - `open`

I think organizing the commands as follows would be better:
- `storage`
  - `status`
  - `encrypted`
    - `close`
    - `open`
  - `hidden`
    - `create`
    - `close`
    - `open`

The background is that I can't seem to find a good way to fit the changing of the read-write status of the *unencrypted* volume in the existing design. Also, if we later add support for changing the read-write state of the *encrypted* volume (I think that needs `nitrokey` support first, I've added a task), we will clash if we just have, say, a `set` in the `storage` subcommand.

In a way the proposed structure makes more sense, because logically there are three distinct volume types the user cares about. Now we could argue that the hidden volume is inside the encrypted volume and that should be reflected in there, but to me that's more of an implementation detail (although it has a bit of relevance to the user) and that would just make the structure ugly and hard to remember (`nitrocli encrypted hidden what`?).

I guess we could make do with the existing structure, at least for the two commands mentioned above, e.g., by creating a `set` command that accepts values such as `unencrypted-ro`, `unencrypted-rw`, `encrypted-ro`, `encrypted-rw` but I don't think that is intuitive.

Comments? @robinkrahl ?

Perhaps while at it...I am a bit confused about the comment for `NK_set_encrypted_read_only`:
```c
	/**
	 * Make encrypted volume read-only.
	 * Device hides encrypted volume for a second therefore make sure
	 * buffers are flushed before running.
	 * Firmware range: v0.49 only, future (see firmware release notes)
	 * Storage only
	 * @param admin_pin 20 characters
	 * @return command processing error code
	 */
```

So I guess that function is not available on recent firmware. But do I understand correctly that the command may come back in the future?

**Comment by szszszsz** [comment]
@robinkrahl Indeed, there is no comment about that. Corrected. It was planned to be fixed asap, but OTP development got higher priority now. It is on the roadmap, and it should be available in the future firmware.

Added description to [v0.50] release:
> Encrypted Volume read-only/read-write mode changing feature was suspended, due to side-effect in current implementation - removing (as in locking) the whole Encrypted Volume for a short period, which could end up in user data loss (due to not sync'ed host OS buffers).
Related issue: #55

[v0.50]: https://github.com/Nitrokey/nitrokey-storage-firmware/releases/tag/0.50

**Comment by robinkrahl** [comment]
@szszszsz Thanks for clearing this up!

**Comment by robinkrahl** [comment]
Added support for the encrypted volume mode in nitrocli in [commit ad76653b3be57c0cfd31c8056a8d68537034324e](https://git.ireas.org/nitrokey-rs/commit/?h=next&id=ad76653b3be57c0cfd31c8056a8d68537034324e).

**Comment by d-e-s-o** [comment]
> Added support for the encrypted volume mode in nitrocli in [commit ad76653b3be57c0cfd31c8056a8d68537034324e](https://git.ireas.org/nitrokey-rs/commit/?h=next&id=ad76653b3be57c0cfd31c8056a8d68537034324e).

Awesome! I guess I'll wait with the implementation on the `nitrocli` side, though, because it is just rather confusing and a lot of documentation overhead if it is only available for `0.49` right now.

> I also thought about a similar solution, but I wasn’t really happy with it because it is rather complex. What do you think about making the hidden and encrypted subcommands into top-level commands?

What would be the top level commands? `storage`, `encrypted`, `hidden`? Or `unencrypted`, `encrypted`, `hidden`?

The first one does not really make sense. The hidden and encrypted volumes are storage so that seems illogical. The second one does not allow us to provide a general storage status. I guess we could move that back (at least in parts) into the `status` command. Not sure.

**Comment by robinkrahl** [comment]
> What would be the top level commands? `storage`, `encrypted`,
> `hidden`? Or `unencrypted`, `encrypted`, `hidden`?

The latter.  The status could be moved to the top-level status command.

> The first one does not really make sense. The hidden and encrypted
> volumes are storage so that seems illogical. The second one does not
> allow us to provide a general storage status. I guess we could move
> that back (at least in parts) into the `status` command. Not sure.

Yeah, it’s not perfect, but I think it’s better than three levels of
nested subcommands.

**Comment by d-e-s-o** [comment]
> What would be the top level commands? `storage`, `encrypted`, `hidden`? Or `unencrypted`, `encrypted`, `hidden`?
> The latter. The status could be moved to the top-level status command.

Okay! Let me look into that as part of the addition of the read-write state of the unencrypted volume change.
