### ISSUE TITLE
nictrocli can't find device

### ISSUE THREAD

**Issue by aschleifer** [d-e-s-o/nitrocli#91]
Hi,

I'm on archlinux and I have the problem that the nitrocli doesn't detect my "Nitrokey Storage 2" even so it is connected and the normal nitrokey-app sees it. i tried to get some more information with verbose output:

```
╰─ nitrocli -vvv status 
[Thu Aug 22 15:06:22 2019][DEBUG_L1]	Connection success: 0 ()
[Thu Aug 22 15:06:22 2019][DEBUG_L1]	Connection success: 0 ()
[Thu Aug 22 15:06:22 2019][DEBUG_L1]	Disconnection: handle already freed: 1 ()
[Thu Aug 22 15:06:22 2019][DEBUG_L1]	Disconnection: handle already freed: 1 ()
Nitrokey device not found
```

**Comment by d-e-s-o** [comment]
Have you made sure to close `nitrokey-app` before trying `nitrocli`?

Also see "Known Problems" section in the [README](https://github.com/d-e-s-o/nitrocli/blob/master/nitrocli/README.md).

**Comment by aschleifer** [comment]
I'm sorry to say I haven't read the README to that extend. Thanks for the information. I will close this issue now and add myself as a watcher to the upstream issue.
